#!/usr/bin/env python2

if __name__ == '__main__':
    from untwisted.plugins.rapidserv import RapidServ, DebugRequest
    from untwisted.network import xmap
    from untwisted.iostd import ACCEPT
    from optparse import OptionParser
    import os

    parser   = OptionParser()
    parser.add_option("-a", "--addr", dest="addr",
                      metavar="string", default='0.0.0.0')
                  
    parser.add_option("-p", "--port", dest="port",
                      metavar="integer", default=80)

    parser.add_option("-b", "--backlog", dest="backlog",
                      metavar="integer", default=50)

    parser.add_option("-f", "--folder", dest="folder",
                      metavar="string", default=os.getcwd())

    (opt, args) = parser.parse_args()
    app = RapidServ(opt.folder, os.path.basename(opt.folder))

    def setup(local, con):
        DebugRequest(con)

    xmap(app.local, ACCEPT, setup)
    app.run(opt.addr, opt.port, opt.backlog)









