#! /usr/bin/env python2

if __name__ == '__main__':
    from untwisted.plugins.rapidserv import RapidServ, Locate, DebugPost, DebugGet
    from untwisted import core

    FOLDER = '.'
    app = RapidServ('0.0.0.0', 1234, 5)
    app.add_handle(Locate, FOLDER)
    app.add_handle(DebugPost)
    app.add_handle(DebugGet)
    core.gear.mainloop()






