#!/usr/bin/env python2

if __name__ == '__main__':
    from untwisted.plugins.rapidserv import RapidServ, DebugRequest
    from untwisted.network import xmap, core
    from untwisted.iostd import ACCEPT
    import argparse
    import os


    parser = argparse.ArgumentParser()
    parser.add_argument('-a', '--addr',  default='0.0.0.0', help='Address')
    parser.add_argument('-p', '--port', type=int, default=80, help='Port')
    parser.add_argument('-b', '--backlog',  type=int, default=50, help='Port')
    parser.add_argument('-f', '--folder',  default=os.getcwd(), help='Folder')

    args = parser.parse_args()
    app  = RapidServ(args.folder, os.path.basename(args.folder))

    def setup(local, con):
        DebugRequest(con)

    xmap(app.local, ACCEPT, setup)
    app.bind(args.addr, args.port, args.backlog)
    core.gear.mainloop()









